# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  release:
    cmds:
      - cargo fix --allow-dirty
      - cargo fmt
      - |
        cargo bump minor
        export VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version' | tr -d '\n')
        echo $VERSION
        git add -A .
        git commit -am "release: v${VERSION}"
        git tag ${VERSION}
        git push origin main --tags
        cargo publish
    silent: true
